### ISSUE TITLE
Support for RowOffset?

### ISSUE THREAD

**Issue by CasperWSchmidt** [lethek/CsvHelper.Excel.EPPlus#5]
Hi

Nice library! I've been chasing an option for decrypting excel files and reading with CsvHelper so this is really nice!

However, CsvHelper.Excel previously had support for RowOffset (skipping fx. 2 "header" lines with logo etc. before the actual header with column names). I had a local copy re-implementing this functionality for CsvHelper.Excel since it is not really actively maintained. 

I would like to make a PR for this here though as it seems like this repo is actively maintained :)

**Comment by lethek** [comment]
Thanks Casper! Your PR is very welcome. I'll check it out tomorrow when I'm back on my PC.

**Comment by lethek** [comment]
I've also now had a look at the project I originally forked from. I notice it dynamically applies the offset during each read rather than acting as an initializer for the Row property.

Having RowOffset initialize Row like you've done is nice and simple and there's not much that can go wrong with it I think, although it does change what the Row property value represents.

However, I'm thinking at some point later when I've a little more time whether it's worth changing to work like the original RowOffset and also adding ColumnOffset support. I want to understand though whether that would break anything for you:

Do you have code that relies on the value of the Row property at all?

**Comment by lethek** [comment]
By the way, just on a related note in case you weren't aware - the ExcelParser in this project does also offer an alternative to this RowOffset feature.

Although it's not as friendly, you can use the ExcelParser constructor overload which takes an ExcelRange parameter to achieve the same effect:

https://github.com/lethek/CsvHelper.Excel.EPPlus#loading-records-from-an-excelrange

**Comment by CasperWSchmidt** [comment]
Yeah thats true. Also I noted that some of our tests started to fail because we do some "skip header lines" in a pre-processing step when more than a single header is present. Often the first header line is just empty and therefore we used to skip it using CsvHelper.Excel, but using the ranges in EPPlus it has already discarded those rows :)

**Comment by lethek** [comment]
@CasperWSchmidt I plan to update the changelog, tag and push out a new package to nuget.org tomorrow.

If I don't get to it though and you need the latest package in the meantime, you can always get the latest "pre-release" build (currently v30.0.2-ci0010 which includes your PR) from my repository here:  https://www.myget.org/F/lethek/api/v3/index.json

**Comment by CasperWSchmidt** [comment]
> Having RowOffset initialize Row like you've done is nice and simple and there's not much that can go wrong with it I think, although it does change what the Row property value represents.

IMHO Row represents the actual row (counting only rows with data), whereas RawRow is the row number in the raw file disregarding data etc.

> However, I'm thinking at some point later when I've a little more time whether it's worth changing to work like the original RowOffset and also adding ColumnOffset support. I want to understand though whether that would break anything for you:
Do you have code that relies on the value of the Row property at all?

Supporting ColumnOffset would be nice i guess :) We don't rely on the Row value at all :)
